### DISCUSSION TITLE
Output to YAML frontmatter

### DISCUSSION THREAD

**Discussion by Taitava** [Taitava/obsidian-shellcommands#307] [Ideas]
[Obsidian `1.1.0` has a new metadata API](https://github.com/obsidianmd/obsidian-api/blob/master/CHANGELOG.md#new-metadata-api) that looks like an easy way to modify YAML frontmatter sections of e.g. the current file.

Imagine the following YAML section:
```yaml
---
tags:
  - aTagThatWillDisappear
deletableValue: "Goodbye!"
myValue: "This text will stay."
---
```

I'd like to create a new output channel that would interpret the output content, letting it to perform different kinds of actions on the YAML frontmatter:
 - Set YAML value, e.g. `tags: [tag1, tag2]`
 - Delete YAML value, e.g. `-deletableValue`
 - Delete all YAML values `*overwrite*` (only applicable if defined as the first line of output). Meaningful if the aim is to write a new YAML section from a scratch.
 - Add to YAML value,  e.g. `tags+: newTag` creates a new list item, or if it's a single value instead of a list `myValue+: " Added text."`
 - Anything else?

These actions would turn the above shown YAML example to:
(`*overwrite*` is not taken into account.)
```yaml
---
tags:
  - tag1
  - tag2
  - newTag
myValue: "This text will stay. Added text."
---
```

The syntax is just a quick draft idea, I haven't made any decisions on it yet.

## Multifile editing

Maybe also make it possible to alter multiple files' YAML sections? Syntax example:
```yaml
File path here, or @ if it's the currently focused file.
Another file path here. (In case same alterations are wanted to be done on multiple files).
---
tags: [tag1, tag2]
-deletableValue
---
Third file path here.
---
tags+: aTagThatWillBeAddedToTheThirdFile
---
```
