### DISCUSSION TITLE
Option to use metadata list item as tokens to command

### DISCUSSION THREAD

**Discussion by jeetsukumaran** [Taitava/obsidian-shellcommands#337] [Ideas]
I have some front matter that specifies a command to be executed to view/edit/cd to a various project directories.

```
project-links:
 - title: "Manuscript Directory"
   directory: "/home/user/projects/p1/manuscript"
   open-command: "gnome-terminal"
 - title: "Manuscript"
   directory: "/home/user/projects/p1/manuscript"
   open-command: "nvim src/p1.tex"
 - title: "Something else"
   directory: "/home/user/projects/p1/manuscript"
   open-command: "command --args1 --args2 src/p1.tex"
```

And I have the following shell commands defined:

- ``cd {{yaml_value:production-links.0.directory}} && {{yaml_value:production-links.0.open-command}}``
- ``cd {{yaml_value:production-links.1.directory}} && {{yaml_value:production-links.1.open-command}}``
- ``cd {{yaml_value:production-links.1.directory}} && {{yaml_value:production-links.2.open-command}}``
etc.

This works for the first case, but for the second and third I have to disable escaping variables fpr the command to work:

- ``cd {{yaml_value:production-links.1.directory}} && {{!yaml_value:production-links.1.open-command}}``
- ``cd {{yaml_value:production-links.1.directory}} && {{!yaml_value:production-links.2.open-command}}``

The recommendation NOT to disable escaping (https://publish.obsidian.md/shellcommands/Variables/Escaping+special+characters+in+variable+values), makes me think of alternate ways to doing this.

One option to add separate metadata for each argument:

```
production-links
 - title: "Manuscript"
   directory: "/home/user/projects/p1/manuscript"
   open-command: "nvim"
   open-arguments: "src/p1.tex"
```

- ``cd {{yaml_value:production-links.0.directory}} && {{yaml_value:production-links.0.open-command}} {{yaml_value:production-links.0.open-arguments}}``

This works in the simple case (i.e., single argument), but that gets out of control as the number of arguments might vary and increase and need to be anticipated.

Another option would be if Shell Command has an option that can "expand" a list argument with a separator. For example ``{{yaml_value:production-links.0.open-command:join(" ")}}``

Then the YAML could be:

```
production-links
 - title: "Manuscript"
   directory: "/home/user/projects/p1/manuscript"
   open-command: ["nvim", "--arg1", "--arg2", "src/p1.tex"]
```

And the shell command is also a lot simpler:

- ``cd {{yaml_value:production-links.0.directory}} && {{yaml_value:production-links.0.open-command:join(" ")}}``

Another syntax could be like the disable token, e.g. ``{{@yaml_value:production-links.0.open-command}}``
