### ISSUE TITLE
{{yaml_value:property_name}} variable

### ISSUE THREAD

**Issue by Taitava** [Taitava/obsidian-shellcommands#120]
### Discussed in https://github.com/Taitava/obsidian-shellcommands/discussions/56

Gives a single value from the current file's YAML frontmatter.
- Parameter `:property_name` refers to a single property whose value will be retrieved.
- The property must have a literal value (a single string or a single number). If it contains a list of values, an error will be shown.
- Nested properties can be accessed with a dot `.` notation:
  ```YAML
  ---
  cssclass:  some-class
  book_details:
    author: "Me!"
    title: "My life"
    description: "A miserable story......"
    chapters:
      first: "Birth"
      second: "Childhood"
      third: "Etc..."
  ---
  ```
  The value of the first chapter can be retrieved with `{{yaml_value:book_details.chapters.first}}`.
- Similarly, list items can be accessed like this:
  ```YAML
  ---
  cssclass: some-class
  tags:
    - first-tag
    - second-tag
  ---
  ```
  First tag: `{{yaml_value:tags.0}}`
  Second tag: `{{yaml_value:tags.1}}`
  So lists are 0-indexed!
  (Note that for [Obsidian tags](https://help.obsidian.md/How+to/Working+with+tags), you cannot access inline tags with this variable - only tags that are defined in the YAML frontmatter.)

**Comment by FelipeRearden** [comment]
This is absolutely FANTASTIC @Taitava !!!!!!!!!!! 👀 👀 👀 👀 👀 👀 👀 👀 👀 👀 👀 👀 👀 👀 👀 👀 👀

**Comment by Taitava** [comment]
And one more detail: E.g. `{{yaml_value:tags.-1}}` reads the last item from the `tags` list. And `{{yaml_value:tags.length}}` gives the number of items in the list. But these two only work for ordered lists, not key-value pair lists:

```yaml
---
ordered_list_has_a_length_property: # and can use .-1 .-2 etc. indexes
  - first-tag
  - second-tag

key_value_pair_list_does_not_have_a_length_property:
  key1: value1
  key2: value2
---
```
