### ISSUE TITLE
{{yaml_value}}: Crash if a queried property has a null value

### ISSUE THREAD

**Issue by Taitava** [Taitava/obsidian-shellcommands#277]
With this kind of YAML in currently open file:
```
---
test_suite_version: 0.16.0
tags:
  - frontmatter-tag
  - this-should-not-appear-twice
yaml_test1:
  first_item: first_value
  middle_item:
  last_item: last_value
yaml_test2:
  - first-item
  - second-item
  - last-item
---
```

Note that `middle_item` has no value!

This shell command: `echo "YAML test: A1. "{{yaml_value:yaml_test1.first_item}}" A2. "{{yaml_value:yaml_test1.middle_item.inner_item}}" A3. "{{yaml_value:yaml_test1.last_item}}" B) first: "{{yaml_value:yaml_test2.0}}" B) second: "{{yaml_value:yaml_test2.1}}" B) last: "{{yaml_value:yaml_test2.-1}}" B) count: "{{yaml_value:yaml_test2.length}}  >> TestResults.md`

Produces this crash:

![kuva](https://user-images.githubusercontent.com/13002142/198823954-864967e4-683c-42c9-83d3-00d2fa5e0219.png)

TODO:
 - [ ] Research for affected versions.
 - [ ] Fix the bug
